---
- name: Testing app
  hosts: vagrant
  tasks:

  - name: Check resonce code
    uri:
      url: "http://{{ansible_ssh_host}}/"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 5
    delay: 1

  - name: Check uptime
    become: yes
    become_user: root
    shell: ls -al /proc | grep tomcat